### ISSUE TITLE
Support printer with interface

### ISSUE THREAD

**Issue by yonderblue** [patrikeh/go-deep#16]
Would be great to support passing in an interface for the printer that the batch trainer uses, in order to implement custom stopping depending on loss. So loss would need to be part of the interface signature in numeric form.

**Comment by gaillard** [comment]
The hacky but demonstrable https://github.com/gaillard/go-deep/commit/f985129cf81deeed512abeed5ec82b851af8d55b. Probably needs other stuff to be refactored to make sense in the repo though. For example I'm not sure as to the rationale for some params in the Train func vs in the New for batch trainer, or how it plays into the accuracy stuff.

**Comment by patrikeh** [comment]
Open to PR:s on that!
