### ISSUE TITLE
Save Neural struct in Disk

### ISSUE THREAD

**Issue by cepalle** [patrikeh/go-deep#21]
Hello,

I am trying to save the Neural structure to disk using "encoding / gob" but it seems that it does not work. Am I doing something wrong or should I use something else?

thank you

**Comment by patrikeh** [comment]
You can get/reconstruct a json representation using `b, _ := neural.Marshal()` and `neural, _ := deep.Unmarshal(b)`. 

Or otherwise `d, _ := neural.Dump()` and marshal the result of that, then reconstruct with `deep.FromDump(d)`.

https://github.com/patrikeh/go-deep/blob/master/persist.go

**Comment by cepalle** [comment]
Thank you very much
