### ISSUE TITLE
ReLU is not correct.

### ISSUE THREAD

**Issue by MichailVestnik** [patrikeh/go-deep#30]
Hi! 

There is a code in the activation.go:

```go
func (a ReLU) F(x float64) float64 { return math.Max(x, 0) }

func (a ReLU) Df(y float64) float64 {
	if y > 0 {
		return 1
	}
	return 0
}
```
This is no correct! 
The right option:

```go
func (a ReLU) F(x float64) float64 { return math.Max(x, 0) }

func (a ReLU) Df(y float64) float64 {
	if y < 0 {
		return 1
	}
	return 0
}
```
For example: https://github.com/FluxML/NNlib.jl/blob/master/src/activations.jl

## Q

Do you plan to develop the library further?
Thanks!

**Comment by patrikeh** [comment]
The derivative of ReLU is 1 for `x > 0`.

I have no plans to further develop this library, but will accept PR with a decent motivation.
