### ISSUE TITLE
Using interfaces for activation and loss functions.

### ISSUE THREAD

**Issue by NDari** [patrikeh/go-deep#8]
Currently there are a few Activation/Loss functions which are provided in go-deep. While internally these functions follow an interface, this is not completely exposed to the clients of this library. For example, If I would like to experiment with a new activation function I would not be able to without modifying the code in go-deep.

If we can expose the ability for clients of this library to provide their own activation functions by providing types that implement the `Differentiable` and `Loss` interfaces, I think the flexibility of this library will be greatly increased.

If this is something that sounds reasonable, I would be more than happy to take a crack at implementing this and submitting a merge request.

**Comment by patrikeh** [comment]
That would indeed be nice. The primary reason I did not use the interfaces directly was in order to make things serializable, and I'd prefer to keep that aspect intact. If there’s a way to accomplish both goals I’m definitely open.

**Comment by NDari** [comment]
Sorry I missed that aspect. I will have to think about this a bit. The most strightforward way would be (i think) to require them to also implement the `Marshaller` and `Unmarshaller` interfaces so that those objects can encode/decode themselves.

This feels like a big requirement if you dont care about that. There are a few ways we can solve this issue. One idea would be to lose the ability to serialize if the implementers of Loss or Differentiable do not also implement the marshalling interfaces. This may be ok if we document this, and explicitly prevent the serialization from happening if the marshalling interfaces are not implemented to prevent any surprises.

What are your thoughts about this? Do you have a hard requirement for your network to be always serializable?

**Comment by patrikeh** [comment]
I still don't see how that might solve the issue since functions can't be serialized in go. The easiest way that I can think of would be some kind of ```OverrideActivation``` parameter in the config, that, when set, prohibits serialization. But it doesn't feel super clean.

The ```Loss``` functions on the other hand could be moved to the ```training``` package and be exposed as a pluggable interface, as you mentioned.
